// Custom Learning Hub article data. Wording preserved.
export const CUSTOM_LEARNING_ARTICLES = {
  'pokemon-team-cores': {
    title: 'What Is a Core?', subtitle: 'The small group of Pokémon your team is built around.',
    body: [
      'A core is a group of two or three Pokémon that are chosen because they work especially well together. They are not the whole team yet — they are the foundation the rest of the team is built around.',
      'A good core gives your team a clear direction. The Pokémon in the core might cover each other’s weaknesses, create safe turns for each other, share a tactic, pressure the same answers, or combine offense and support so the main plan works more often.',
      'In Pokémon Champions, you can think of a core as the part of your team that explains what the team is trying to do. Once the core is clear, the remaining slots are easier to choose because they should support, protect, or complete that core.'
    ],
    sections: [
      ['Common types of cores', ['Offensive cores use two or more attackers to pressure different answers.', 'Defensive cores use typings, bulk, abilities, or switching to make the team safer.', 'Support and setup cores pair a Pokémon that needs help with a partner that gives it safe turns.', 'Weather, terrain, Tailwind, and Trick Room cores are built around enabling a shared battle plan.']],
      ['What makes a core good?', ['The Pokémon help each other instead of acting like six separate picks.', 'The core has a clear reason for existing.', 'The core can make progress in real battles.', 'The rest of the team can be built around what the core needs.']],
      ['Beginner mistake to avoid', ['Do not add every Pokémon only because it counters one different threat.', 'A team can become hard to pilot if the Pokémon do not support the same plan.', 'It is fine to cover weaknesses, but the core should still keep the team focused.']]
    ],
    examples: [
      '“I paired Ninetales (Alolan Form) with a setup attacker because Aurora Veil gives safer setup turns.”',
      '“I paired Kangaskhan (Mega) with a strong attacker because Fake Out can create a safer attack turn.”',
      '“I built a Trick Room core with a setter and slow attackers that become dangerous once Trick Room is active.”',
      '“I added a defensive partner because my main Pokémon has a weakness that needs safer switching support.”'
    ],
    buttons: ['team-building-guide','metadex','team-builder']
  },

  'adding-to-a-core': {
    title: 'Adding to a Core', subtitle: 'Choosing teammates that make your main idea stronger, safer, or easier to execute.',
    body: [
      'Once you understand what a core is, the next step is adding Pokémon that help that core work in battle.',
      'A good addition should support the main plan instead of pulling the team in a completely different direction. You are not trying to answer every possible matchup yet — you are trying to make the core functional.',
      'At this stage, think in broad jobs: extra damage, safer switching, support tools, speed control, or direct enabling for the main Pokémon or core.'
    ],
    sections: [
      ['Good reasons to add a Pokémon', ['It adds complementary offense, such as coverage, priority, spread pressure, or a second attacker.', 'It adds complementary defense, such as safer switch-ins, useful resistances, bulk, or defensive utility.', 'It provides support, such as Fake Out, redirection, screens, Taunt, status, weather, or disruption.', 'It gives speed control through Tailwind, Trick Room, Icy Wind, Thunder Wave, priority, or similar tools.', 'It directly enables the core, such as setting weather, creating safe setup turns, or covering a key weakness.']],
      ['Beginner mistake to avoid', ['Do not add six separate Pokémon that each counter one different thing but do not work together.', 'Covering weaknesses is important, but every addition should still belong to the team’s main plan.', 'If a Pokémon does not help the core function, it may be better saved for a different team.']]
    ],
    examples: [
      '“I added Fake Out support so my main attacker can get a safer turn.”',
      '“I added Trick Room because my main attackers are powerful but slow.”',
      '“I added a bulky switch-in because my core dislikes a common attack type.”',
      '“I added a second attacker because my first core did not apply enough pressure.”'
    ],
    buttons: ['team-building-guide','metadex','team-builder','analysis-desk']
  },

  'safe-turns': {
    title: 'Safe Turns', subtitle: 'Creating turns where your important Pokémon can act without being punished too hard.',
    body: ['Many strong Pokémon need help getting useful turns. A team with strong attackers but no safe turns may struggle because those attackers get removed before doing their job.', 'Safe turns can be created by Fake Out, Protect, redirection, screens, speed control, defensive switching, Intimidate-style effects, forcing the opponent to defend, threatening knockouts, and good positioning.'],
    examples: ['“Fake Out gives my setup Pokémon one safer turn.”','“Aurora Veil helps my team survive attacks while setting up.”','“Tailwind lets my attacker move first instead of taking damage first.”','“Protect lets me avoid a double target while my partner attacks.”'], buttons: ['team-building-guide','metadex','team-builder']
  },
  'offensive-pressure': {
    title: 'Offensive Pressure', subtitle: 'Making the opponent respect your damage.',
    body: ['Offensive pressure means your Pokémon threaten meaningful damage, knockouts, setup, or board control.', 'Pressure can come from strong attacks, spread moves, priority, setup threats, type coverage, speed advantage, forcing Protect, threatening both opposing Pokémon, and endgame cleaning. If a team has too little pressure, the opponent can ignore it, set up freely, or remove your support Pokémon first.'],
    examples: ['“This Pokémon threatens a knockout if ignored.”','“Spread damage pressures both opponents.”','“Priority lets me finish weakened Pokémon.”','“Setup pressure forces the opponent to respond immediately.”'], buttons: ['team-building-guide','metadex','damage','team-builder']
  },
  'positioning': {
    title: 'Positioning', subtitle: 'Getting the right Pokémon on the field at the right time.',
    body: ['Positioning is about which Pokémon are active, which Pokémon are in the back, and how safely you can move between them.', 'It includes choosing leads, switching safely, using Protect, preserving win conditions, bringing the right four Pokémon, keeping support next to the Pokémon it enables, avoiding bad board states, and creating good board states. A team can be strong on paper but awkward if it cannot position its important Pokémon safely.'],
    examples: ['“I lead Fake Out next to my attacker to create pressure immediately.”','“I keep my cleaner in the back until faster threats are weakened.”','“I switch my resist into an attack to preserve my main Pokémon.”','“I use Protect to let my partner remove a threat.”'], buttons: ['team-building-guide','team-builder','analysis-desk']
  },
  'theory-checking-a-team': {
    title: 'Theory Checking a Team', subtitle: 'Imagining battles before full playtesting.',
    body: ['Theory checking means mentally testing whether your team idea makes sense before polishing every detail.', 'Ask what you would lead, which four Pokémon you would bring, what you would leave behind, how you create a safe turn, how you apply pressure, what happens if the first plan is stopped, and which matchups already look uncomfortable. It is not a replacement for real battles, but it catches obvious problems early.'],
    examples: ['“If I cannot imagine ever bringing one Pokémon, it may not belong.”','“If I cannot explain how the team wins, the core may need more focus.”','“If every matchup needs a different answer, the team may lack cohesion.”','“If my attacker has no safe way to attack, I may need support or speed control.”'], buttons: ['team-building-guide','team-builder','analysis-desk','matchups']
  },
  'complementary-offense': {
    title: 'Complementary Offense', subtitle: 'Adding damage that helps your core pressure more matchups.',
    body: ['Complementary offense means adding Pokémon that improve how your team deals damage.', 'It is not only about type coverage. It can also mean physical/special balance, priority moves, spread moves, speed advantage, setup pressure, endgame cleaning, forcing Protects, or threatening Pokémon your core struggles to damage.'],
    examples: ['“My core is mostly special damage dealers, so I added a physical damage dealer.”','“My team struggles to hit Steel-types, so I added Fire or Fighting pressure.”','“My team needs a cleaner that can finish weakened opponents.”','“My team wants spread damage so both opponents are pressured at once.”'], buttons: ['team-building-guide','metadex','team-builder']
  },
  'complementary-defense': {
    title: 'Complementary Defense', subtitle: 'Adding Pokémon that make switching, positioning, and surviving easier.',
    body: ['Complementary defense means adding Pokémon that help the team take hits, switch safely, or reduce pressure.', 'It is not only about type resistances. It can include Intimidate-style effects, useful immunities, bulky stats, recovery, defensive abilities, weather or terrain protection, pivoting, safer switch-ins, and covering shared weaknesses.'],
    examples: ['“My core is weak to Ground, so I added a Flying-type or Ground immunity.”','“My team is frail, so I added a bulky support Pokémon.”','“My main attacker needs safe switches, so I added defensive utility.”','“My team keeps losing to physical damage dealers, so I added attack reduction or a bulky resist.”'], buttons: ['team-building-guide','metadex','team-builder','analysis-desk']
  },
  'support-options': {
    title: 'Support Options', subtitle: 'Helping your main Pokémon get safe and useful turns.',
    body: ['Support Pokémon help other Pokémon succeed through tools like Fake Out, redirection, screens, healing, Taunt, status, disruption, weather, terrain, Helping Hand-style damage boosting, and defensive pivots.', 'Support Pokémon should still help the team make progress. A team with too much passive support can struggle to actually win.'],
    examples: ['“I added Fake Out so my setup Pokémon can get a safer turn.”','“I added redirection so my attacker is harder to stop.”','“I added screens so my team can survive longer.”','“I added Taunt because opposing setup or Trick Room was a problem.”'], buttons: ['team-building-guide','metadex','team-builder']
  },
  'speed-control': {
    title: 'Speed Control', subtitle: 'Learn why moving before your opponent matters and what tools help your team control turn order.',
    body: ['Speed control means using moves, abilities, items, or team structure to influence which Pokémon move first.', 'It is not only about having fast Pokémon. Slow teams can control Speed too, especially with Trick Room.'],
    examples: ['“My attackers are strong but slow, so I added Trick Room.”','“My team is fast but still loses to faster offense, so I added Tailwind.”','“I added Icy Wind because it gives speed control while still dealing damage.”','“I added priority because it lets me finish weakened targets even when I am slower.”'], buttons: ['team-building-guide','metadex','team-builder','analysis-desk']
  }
,
  'learning-team-breadth': { title: 'Team Breadth', subtitle: 'Helping your team handle a wider range of matchups.', body: ['Breadth means adding tools that let your team play into more opponents.', 'Breadth should widen what your team can handle without making the team lose its main plan.'], sections: [['Breadth can come from', ['better type coverage','speed control','defensive answers','support tools','stronger matchup coverage','a Pokémon that helps into a common archetype','a move or ability that patches an obvious hole']]], examples: ['My team struggles into fast offense, so I added speed control.','My team struggles into bulky teams, so I added setup pressure.','My team has no good switch into a common attack type, so I added a resist or immunity.','My team struggles to damage one type, so I added coverage for it.'], buttons: ['team-building-guide','metadex','analysis-desk','matchups'] },
  'learning-team-depth': { title: 'Team Depth', subtitle: 'Giving your core more ways to play.', body: ['Depth means your team has multiple useful interactions around the same main idea.', 'Depth is different from randomly adding answers. It should make the team’s existing plan more flexible.'], sections: [['Depth can come from', ['different lead options','multiple support partners','different ways to create safe turns','alternate offensive partners','pivots','secondary attackers','Pokémon that work with more than one teammate']]], examples: ['My main attacker can lead with Fake Out support or speed control support.','My weather setter supports more than one teammate.','My bulky support helps both my setup Pokémon and my cleaner.','My team can play aggressively or defensively depending on the matchup.'], buttons: ['team-building-guide','metadex','team-builder','analysis-desk'] },
  'learning-team-modes': { title: 'Team Modes', subtitle: 'Adding another plan your team can use in battle.', body: ['A mode is a small package of Pokémon that work together to give the team another direction.', 'A mode usually needs at least two Pokémon that support each other. Adding only one Pokémon often is not enough to create a real mode.'], sections: [['Common examples', ['Trick Room mode','Tailwind mode','weather mode','setup mode','defensive balance mode','fast offense mode','endgame cleaner mode']]], examples: ['A slow attacker plus a Trick Room setter can create a Trick Room mode.','A weather setter plus a weather abuser can create a weather mode.','A screen setter plus a setup attacker can create a setup mode.','A fast support Pokémon plus a strong attacker can create an aggressive lead mode.'], buttons: ['team-building-guide','metadex','team-builder'] },
  'learning-utility': { title: 'Utility', subtitle: 'Useful tools that help your team function.', body: ['Utility means useful non-damage value a Pokémon brings to the team.', 'Utility is valuable when it helps your team execute its plan. Utility that does not support the team’s plan can become passive or unnecessary.'], sections: [['Utility can include', ['Fake Out','Taunt','redirection','screens','healing','speed control','weather','terrain','disruption','pivoting','status','defensive abilities','priority','recovery']]], examples: ['Fake Out helps create a safe turn.','Taunt stops opposing setup or support.','Redirection protects an important attacker.','Speed control helps my team move first.'], buttons: ['team-building-guide','metadex','team-builder'] },
  'learning-matchups': { title: 'Matchups', subtitle: 'Thinking about how your team plays into opposing teams.', body: ['A matchup is how your team lines up against another Pokémon, core, archetype, or full team.', 'You do not need to solve every matchup before testing, but you should notice obvious problems.'], sections: [['A matchup can depend on', ['type interactions','speed control','damage pressure','defensive answers','support tools','lead options','win conditions','whether your main plan is easy or hard to execute']]], examples: ['My team struggles if the opponent is faster and can KO me first.','My team has no good answer to bulky setup.','My team is strong if I can get Tailwind up safely.','My team has a bad matchup if my main attacker cannot get onto the field safely.'], buttons: ['team-building-guide','matchups','analysis-desk','team-builder'] },
  'learning-team-cohesion': { title: 'Team Cohesion', subtitle: 'Making sure your six Pokémon still feel like one team.', body: ['Cohesion means the Pokémon on the team work together toward a shared plan.', 'A cohesive team can still have multiple modes, but those modes should connect to the overall plan.'], sections: [['A team may lack cohesion if', ['every Pokémon is solving a different problem','there is no clear win condition','support Pokémon do not support the attackers','attackers need different kinds of support that the team cannot provide','the team has too many separate ideas','the leads feel awkward','some Pokémon never get brought']]], examples: ['My team has speed control, attackers that benefit from it, and support that helps them attack safely.','My team lacks cohesion because one Pokémon wants Trick Room while the rest of the team only works outside it.','My support Pokémon are useful because they help my actual win conditions.','My final Pokémon should add something the team needs, not just be individually strong.'], buttons: ['team-building-guide','analysis-desk','team-builder'] },
  'learning-backup-plans': { title: 'Backup Plans', subtitle: 'What your team does when the first plan is stopped.', body: ['A backup plan is another way your team can still win if the main idea is disrupted.', 'A backup plan should not completely replace the main idea. It should give the team flexibility when the first plan is not enough.'], sections: [['Backup plans can include', ['a second attacker','a different lead pair','a slower or faster mode','a defensive endgame','a setup option','priority cleanup','a matchup-specific mode','a Pokémon that wins if the main attacker is removed']]], examples: ['If my main attacker is stopped, I have a second Pokémon that can clean late-game.','If Tailwind is denied, I can still use priority or bulky positioning.','If Trick Room is hard to set, I have Pokémon that can play outside Trick Room.','If my weather plan is disrupted, my team still has neutral damage and support options.'], buttons: ['team-building-guide','metadex','team-builder','analysis-desk'] },

  'learning-movesets': {
    title: 'Movesets',
    subtitle: 'Choosing moves that match a Pokémon’s job.',
    category: 'Finishing Details',
    body: [
      'A moveset is not just four strong moves. A good moveset gives a Pokémon the tools it needs to do its job in real battles.',
      'Most Pokémon want a mix of reliable damage, Protect or another positioning tool, coverage, utility, support, setup, recovery, and speed control. The exact mix depends on the Pokémon’s role and what the team needs.'
    ],
    sections: [
      ['A simple moveset template', ['Protect or positioning tool','Main STAB damage move','Second STAB, coverage, or spread move','Utility, setup, recovery, or extra coverage','This is only a starting point. Some Pokémon need more attacks, some need more support, and some may skip Protect if they have a strong reason.']],
      ['What counts as utility?', ['Utility moves help the team without being mainly about raw damage. Some still deal damage, but their main value is the extra effect.','Examples include Protect, Tailwind, Trick Room, Icy Wind, Electroweb, Thunder Wave, Fake Out, Follow Me, Rage Powder, Taunt, Encore, Snarl, Will-O-Wisp, screens, Aurora Veil, recovery, setup, anti-setup, weather, and pivoting moves.','A move can be utility on one Pokémon but damage on another. Ask: what is the purpose of this move on this Pokémon?']],
      ['Protect', ['Protect lets a Pokémon avoid damage while its partner acts.','It helps avoid double targets, stall Tailwind, Trick Room, weather, terrain, screens, or boosts, scout the opponent, keep a win condition safe, and improve positioning.','Not every Pokémon must always have Protect, but if you remove it, the Pokémon should have a clear reason.']],
      ['Speed control moves', ['Speed control changes which Pokémon move first and is one of the most important tools in Pokémon Champions team building.','Examples include Tailwind, Trick Room, Icy Wind, Electroweb, Thunder Wave, speed-boosting setup moves, and priority moves.','Fast teams often use Tailwind or speed drops. Slow teams may use Trick Room. Balanced teams may use softer speed control like Icy Wind, Thunder Wave, or priority.']],
      ['Redirection', ['Redirection uses moves like Follow Me or Rage Powder to pull single-target attacks away from a partner.','It can protect setup Pokémon, fragile attackers, and important support turns while disrupting the opponent’s targeting.','Redirection does not protect against all spread moves, and the redirecting Pokémon needs enough bulk or disruption value to justify the slot.']],
      ['Fake Out', ['Fake Out is a priority move that can stop one opposing Pokémon from moving on the first turn the user is on the field.','It can create safe setup turns, help a partner attack safely, stop support moves, force defensive play, create tempo, and buy time for speed control.','The best Fake Out users usually have useful bulk, good pressure, or ways to leave and re-enter the field.']],
      ['Taunt and Encore', ['Taunt helps stop Trick Room, setup, recovery, redirection, status moves, screens, and other support.','Encore can punish Protect, setup, passive moves, repeated support moves, and bad positioning.','These moves are strongest when the user is fast enough, bulky enough, or has priority-style support to use them reliably.']],
      ['Status moves', ['Sleep can deny turns. Burn can weaken attack-focused Pokémon. Paralysis can reduce Speed and sometimes stop movement. Poison adds passive damage but may be too slow for many battles. Freeze is powerful but usually unreliable.','Do not add status just because it sounds annoying. Add it because it helps your team’s plan or fixes a real matchup problem.']],
      ['Screens and Aurora Veil', ['Reflect, Light Screen, and Aurora Veil reduce incoming damage and help teammates survive important turns.','They are useful for setup teams, fragile attackers, bulky offense, weather teams, and teams that need safer positioning.','Screens and Aurora Veil cost turns and moveslots. The rest of the team must actually use the extra safety to make progress.']],
      ['Stat-dropping moves', ['Snarl lowers Special Attack. Icy Wind and Electroweb lower Speed. Breaking Swipe lowers Attack. Parting Shot lowers offensive stats while pivoting. Fake Tears lowers Special Defense.','These moves are strong when they help the team survive, reposition, or secure KOs.']],
      ['Setup moves', ['Setup moves boost a Pokémon’s stats so it can become a stronger win condition.','Examples include Swords Dance, Nasty Plot, Dragon Dance, Calm Mind, Bulk Up, and Quiver Dance-style boosts if available.','Setup is powerful but risky because opponents can double-target or disrupt the setup Pokémon. Good setup teams usually need Fake Out, redirection, screens, Aurora Veil, speed control, defensive switching, or strong pressure.']],
      ['Recovery moves', ['Recovery is strongest on Pokémon bulky enough to survive repeated attacks.','It helps defensive pivots, bulky attackers, support Pokémon, and balance teams win longer games.','Examples include Recover, Roost, Wish, Synthesis, and Moonlight-style recovery if available. Recovery is weaker if the Pokémon is too frail or the team needs immediate pressure.']],
      ['Anti-setup moves', ['Haze removes stat boosts. Roar, Whirlwind, or Dragon Tail-style moves can force switches if available. Taunt can stop setup before it happens. Encore can punish setup after it happens.','Anti-setup is most useful when setup Pokémon are common or your team struggles to remove boosted threats quickly.']],
      ['Weather and field moves', ['Sunny Day, Rain Dance, Snowscape, Sandstorm, and terrain moves can support specific team modes.','Manual weather or terrain is usually weaker than ability-based setting, but can still be useful on dedicated teams or as counterplay to opposing weather.']],
      ['How many utility moves should I run?', ['Fast frail attackers often want more damage moves. Bulky support Pokémon may use several utility moves. Setup Pokémon often need Protect plus setup plus reliable attacks. Defensive Pokémon may use recovery, disruption, and one damage move. Offensive support Pokémon may use one or two utility moves while still applying damage.','Every move should have a reason. If you never click a move during testing, it may need replacing.']],
      ['Moveset checklist', ['What is this Pokémon’s job?','Which move helps it do that job most often?','Does it need Protect?','Does it need reliable STAB damage?','Does it need coverage?','Does it need speed control?','Does it need support, disruption, or recovery?','Does this moveset help the team’s main plan?','Is there any move I almost never click?']]
    ],
    examples: [
      'My attacker needs reliable damage first, then coverage or Protect depending on how often it is targeted.',
      'My support Pokémon needs speed control and disruption because its job is to create safer turns.',
      'My setup Pokémon needs Protect or support because opponents can double-target it before it becomes threatening.',
      'My team already has enough damage, so this moveslot can become support if it solves a real problem.'
    ],
    buttons: ['learning-hub','team-building-guide','team-builder','metadex','damage']
  },
  'learning-items': { title: 'Items', subtitle: 'Choosing items that help a Pokémon perform its role.', body: ['Items should support the Pokémon’s job.', 'An item is good if it helps the Pokémon do what the team needs it to do.'], sections: [['Items can help with', ['damage','bulk','recovery','speed','safety','setup','consistency','matchup coverage','avoiding disruption']]], examples: ['My attacker uses a damage item because it needs important KOs.','My bulky support uses a defensive item so it survives longer.','My setup Pokémon uses an item that helps it get going safely.','My matchup answer uses an item that helps it survive the threat it is meant to handle.'], buttons: ['team-building-guide','team-builder','metadex'] },
  'learning-abilities': { title: 'Abilities', subtitle: 'Choosing the ability that best supports the team plan.', body: ['Abilities can define what a Pokémon contributes.', 'Do not choose an ability just because it sounds strong. Choose the one that best supports the Pokémon’s role and the team’s plan.'], sections: [['Abilities can provide', ['damage','bulk','weather','terrain','speed','immunity','disruption','support','consistency','matchup value']]], examples: ['I chose a weather ability because my team uses that weather.','I chose a defensive ability because this Pokémon needs to switch in often.','I chose an offensive ability because this Pokémon is meant to pressure damage.','I chose a speed-related ability because this Pokémon needs to move first.'], buttons: ['team-building-guide','team-builder','metadex'] },
  'learning-natures': { title: 'Natures and Stat Points', subtitle: 'Making a Pokémon’s stats match its job.', body: ['Natures and stat points should support what the Pokémon is meant to do.', 'Early drafts can use simple role-based spreads. Exact optimisation can come later after testing.'], sections: [['Stat investment can help with', ['moving before important targets','surviving important attacks','dealing enough damage','improving consistency','supporting a specific role']]], examples: ['My fast attacker wants Speed and damage.','My bulky support wants enough bulk to survive and keep helping.','My Trick Room attacker may not need much Speed.','My defensive Pokémon invests in the stats that help it survive common attacks.'], buttons: ['team-building-guide','team-builder','damage','analysis-desk'] },
  'learning-stat-points': { title: 'Natures and Stat Points', subtitle: 'Making a Pokémon’s stats match its job.', body: ['Natures and stat points should support what the Pokémon is meant to do.', 'Early drafts can use simple role-based spreads. Exact optimisation can come later after testing.'], sections: [['Stat investment can help with', ['moving before important targets','surviving important attacks','dealing enough damage','improving consistency','supporting a specific role']]], examples: ['My fast attacker wants Speed and damage.','My bulky support wants enough bulk to survive and keep helping.','My Trick Room attacker may not need much Speed.','My defensive Pokémon invests in the stats that help it survive common attacks.'], buttons: ['team-building-guide','team-builder','damage','analysis-desk'] },
  'learning-benchmarks': { title: 'Benchmarks', subtitle: 'Specific damage, survival, or speed goals.', body: ['A benchmark is a specific target your build is trying to reach.', 'Benchmarks are useful, but you do not need many of them before your first test games.'], sections: [['Benchmarks can include', ['survive a specific attack','KO a specific Pokémon','outspeed a specific Pokémon','move after something under Trick Room','survive long enough to use a support move','guarantee a useful damage range']]], examples: ['I want this Pokémon to survive one common super-effective hit.','I want this attacker to KO a common threat with its main move.','I want this Pokémon to outspeed a certain target after speed control.','I want this support Pokémon to survive long enough to set Tailwind or Trick Room.'], buttons: ['team-building-guide','damage','team-builder'] },
  'learning-pokemon-roles': { title: 'Pokémon Roles', subtitle: 'Knowing what each Pokémon is meant to do.', body: ['Every Pokémon should have a job on the team.', 'A Pokémon can have more than one role, but if you cannot explain any role for it, it may not belong.'], sections: [['Common roles', ['main attacker','secondary attacker','cleaner','support','speed control','defensive pivot','setup Pokémon','disruption','matchup answer','enabler']]], examples: ['This Pokémon is my main damage dealer.','This Pokémon creates safe turns with support.','This Pokémon helps me play into fast teams.','This Pokémon is mainly here for one difficult matchup, but still supports the team elsewhere.'], buttons: ['team-building-guide','metadex','team-builder','analysis-desk'] },
  'learning-protect-positioning': { title: 'Protect and Positioning', subtitle: 'Why defensive turns matter in doubles-style battles.', body: ['Protect is often important because it helps with positioning, scouting, avoiding double targets, stalling field effects, and letting a partner act safely.', 'Not every Pokémon must always have Protect, but teams usually need enough positioning tools to avoid being forced into bad trades.'], sections: [['Protect can help', ['avoid obvious attacks','punish double targets','stall Tailwind, Trick Room, weather, or terrain turns','let a partner remove a threat','keep a win condition safe','improve board positioning']]], examples: ['I Protect my threatened Pokémon while its partner attacks.','I use Protect to stall out the opponent’s speed control.','I use Protect because the opponent is likely to double target.','I skip Protect only when the Pokémon has another strong reason to use all four moves.'], buttons: ['team-building-guide','team-builder','analysis-desk'] },

  'learning-testing-teams': { title: 'Testing Teams', subtitle: 'Using real games to improve your first draft.', body: ['Testing is how you check whether your team-building guesses were correct.', 'Do not judge the whole team from one game. Look for patterns across several games.'], sections: [['Testing helps you learn', ['whether your main idea works','which Pokémon you actually bring','which matchups are hard','which moves and items matter','whether your speed control is enough','whether your team has enough damage','whether your support creates safe turns']]], examples: ['I lost because I played badly, not because the team is bad.','I keep losing to the same archetype, so the team may need an adjustment.','This move has not been clicked in five games, so it may need changing.','This Pokémon never gets brought, so it may not fit the team.'], buttons: ['team-building-guide','team-builder','analysis-desk','matchups'] },
  'learning-sixth-pokemon-syndrome': { title: 'Sixth Pokémon Syndrome', subtitle: 'When the final team slot never feels right.', body: ['Sixth Pokémon Syndrome happens when five Pokémon feel useful, but the last slot feels awkward, unused, or disconnected.', 'The fix is not always to keep swapping the sixth Pokémon. Sometimes you need to rethink what the team needs or adjust an earlier slot.'], sections: [['Possible causes', ['the team lacks a clear final need','the core is missing something important','the team is trying to patch too many matchups','one earlier Pokémon is not doing enough','the final slot only counters one thing','the team needs another mode or better cohesion']]], examples: ['If the sixth Pokémon never gets brought, ask what job it was meant to do.','If the sixth Pokémon only helps one matchup, it may need more general value.','If every sixth Pokémon feels wrong, the issue may be the core or team structure.','A good final slot should support the team, not just patch one fear.'], buttons: ['team-building-guide','metadex','team-builder','analysis-desk'] },
  'learning-team-iteration': { title: 'Team Iteration', subtitle: 'Making small improvements after testing.', body: ['Iteration means improving the team step by step.', 'A bad game does not always mean the team is bad. A repeated problem is more useful evidence.'], sections: [['Good iteration means', ['changing one thing at a time when possible','looking for repeated patterns','separating play mistakes from team problems','making small changes before replacing the whole team','returning to earlier steps if the core itself is flawed']]], examples: ['I changed one move because I never clicked the old one.','I changed an item because it never activated or mattered.','I adjusted Speed because I kept moving after important threats.','I replaced a Pokémon because it failed its role across many games.'], buttons: ['team-building-guide','team-builder','analysis-desk','damage'] },
  'learning-win-conditions': { title: 'Win Conditions', subtitle: 'Understanding how your team actually wins games.', body: ['A win condition is the Pokémon, position, or game state that lets your team close out a battle.', 'Testing should show whether your win conditions are realistic.'], sections: [['Win conditions can include', ['a strong attacker','a setup Pokémon','a cleaner in the back','a speed control advantage','a defensive endgame','weather or field control','chip damage plus priority','removing key opposing threats']]], examples: ['My cleaner wins if faster threats are removed first.','My setup Pokémon wins if I create one safe turn.','My bulky endgame wins if I preserve it until the opponent’s damage is gone.','My weather attacker wins if I keep weather control.'], buttons: ['team-building-guide','team-builder','analysis-desk','matchups'] },
  'learning-testing-log': { title: 'Testing Logs', subtitle: 'Tracking what happens so your changes are based on patterns.', body: ['A testing log helps you avoid changing the team based only on frustration after one loss.', 'The goal is not to write an essay after every game. Short notes are enough.'], sections: [['A simple log can track', ['leads used','Pokémon brought','Pokémon left behind','wins and losses','difficult opposing Pokémon','moves that mattered','moves that never got clicked','items that helped','what felt awkward','next change to test']]], examples: ['Brought this Pokémon 0 times in 6 games.','Lost to fast offense three times.','Never clicked this coverage move.','Item helped twice, keep testing.','Lead felt awkward into Trick Room.'], buttons: ['team-building-guide','team-builder','analysis-desk','matchups'] },
  'learning-first-drafts': { title: 'First Draft Teams', subtitle: 'Finishing a usable version before perfecting it.', body: ['The first complete version of a team is not supposed to be perfect.', 'Testing teaches you more than endlessly editing an unfinished team.'], sections: [['The goal of a first draft is to', ['have six Pokémon','have complete moves, items, abilities, natures, and stat points','have a clear plan','be good enough to test','reveal what actually needs changing']]], examples: ['I do not need perfect EVs before my first games.','If a move never gets clicked, I can change it later.','If an item does not help, testing will show that.','If a Pokémon never gets brought, I may need to replace it.'], buttons: ['team-building-guide','team-builder','analysis-desk'] },

};
